version: "3.7"
services:
  postgres:
    container_name: 'dog_postgres'
    image: 'postgres:11.2'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=dog'
      - 'POSTGRES_PASSWORD=password'
